/**
 * Route name -> required permission codes (user must have all).
 * Superuser bypasses in the API; FE mirrors with is_superuser from /me.
 */
export const ADMIN_ROUTE_PERMISSIONS = {
  dashboard: ['DASHBOARD-ACCESS'],
  adminPanel: ['MANAGE-USERS'],
  adminNews: ['READ-NEWS'],
  createNews: ['CREATE-NEWS'],
  editNews: ['UPDATE-NEWS'],
  adminCategories: ['READ-CATEGORY'],
  createCategory: ['CREATE-CATEGORY'],
  editCategory: ['UPDATE-CATEGORY'],
  adminBible: ['READ-DAILY-READING'],
  createDailyReading: ['CREATE-DAILY-READING'],
  editDailyReading: ['UPDATE-DAILY-READING'],
  adminBibleTypes: ['READ-BIBLE'],
  adminBibleTypeCreate: ['WRITE-BIBLE'],
  adminBibleTypeEdit: ['WRITE-BIBLE'],
  adminBibleManagement: ['READ-BIBLE'],
  adminBibleCreate: ['WRITE-BIBLE'],
  adminBibleEdit: ['WRITE-BIBLE'],
  adminChapterList: ['READ-BIBLE'],
  adminChapterCreate: ['WRITE-BIBLE'],
  adminChapterEdit: ['WRITE-BIBLE'],
  adminVerseList: ['READ-BIBLE'],
  adminVerseCreate: ['WRITE-BIBLE'],
  adminVerseEdit: ['WRITE-BIBLE'],
  adminSectionList: ['READ-BIBLE'],
  adminSectionCreate: ['WRITE-BIBLE'],
  adminSectionEdit: ['WRITE-BIBLE'],
  adminSermons: ['READ-SERMON'],
  createSermon: ['CREATE-SERMON'],
  editSermon: ['UPDATE-SERMON'],
  adminMessengerIssues: ['READ-MESSENGER'],
  createMessengerIssue: ['CREATE-MESSENGER'],
  editMessengerIssue: ['UPDATE-MESSENGER'],
  adminGallery: ['READ-GALLERY'],
  adminGalleryCreate: ['CREATE-GALLERY'],
  adminGalleryEdit: ['UPDATE-GALLERY'],
  adminSaints: ['READ-SAINT'],
  createSaint: ['CREATE-SAINT'],
  editSaint: ['UPDATE-SAINT'],
  adminChurchHistory: ['READ-CHURCH-HISTORY'],
  adminStructurePages: ['READ-STRUCTURE-PAGE'],
  createStructurePage: ['CREATE-STRUCTURE-PAGE'],
  editStructurePage: ['UPDATE-STRUCTURE-PAGE'],
};
